source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
use_frameworks!
project '/Users/Ricardo/Documents/Xcode Codes/Lab05/Lab05.xcodeproj'

target 'Lab05' do
pod 'GoogleMaps'
pod 'Google/Analytics'
end
